// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFYeBXyhYZMpsz_DOrVbP8QDgMzcBBoYs',
    appId: '1:904703646853:web:1f9efff2cef0894c1b1dec',
    messagingSenderId: '904703646853',
    projectId: 'rappi-1973b',
    authDomain: 'rappi-1973b.firebaseapp.com',
    storageBucket: 'rappi-1973b.firebasestorage.app',
    measurementId: 'G-8QE60GD3QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjkfsAB0_eRrB66dd0tHTHZsp_11yUgLs',
    appId: '1:904703646853:android:f91d98834cbaa3b91b1dec',
    messagingSenderId: '904703646853',
    projectId: 'rappi-1973b',
    storageBucket: 'rappi-1973b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf36rszBwOewX20q278c2dc9eDJJNpcHY',
    appId: '1:904703646853:ios:f411f7e3fa58adf11b1dec',
    messagingSenderId: '904703646853',
    projectId: 'rappi-1973b',
    storageBucket: 'rappi-1973b.firebasestorage.app',
    iosBundleId: 'com.example.rappi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf36rszBwOewX20q278c2dc9eDJJNpcHY',
    appId: '1:904703646853:ios:f411f7e3fa58adf11b1dec',
    messagingSenderId: '904703646853',
    projectId: 'rappi-1973b',
    storageBucket: 'rappi-1973b.firebasestorage.app',
    iosBundleId: 'com.example.rappi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFYeBXyhYZMpsz_DOrVbP8QDgMzcBBoYs',
    appId: '1:904703646853:web:1f9efff2cef0894c1b1dec',
    messagingSenderId: '904703646853',
    projectId: 'rappi-1973b',
    authDomain: 'rappi-1973b.firebaseapp.com',
    storageBucket: 'rappi-1973b.firebasestorage.app',
    measurementId: 'G-8QE60GD3QS',
  );

}